var namespace_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific =
[
    [ "MobileInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_mobile_input.html", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_mobile_input" ],
    [ "StandaloneInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_standalone_input.html", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_standalone_input" ]
];